ALTER TABLE "transaction" DROP CONSTRAINT "type_check";--> statement-breakpoint
ALTER TABLE "transaction" DROP CONSTRAINT "transaction_budget_id_budget_id_fk";
--> statement-breakpoint
ALTER TABLE "transaction" DROP CONSTRAINT "transaction_pot_id_pot_id_fk";
--> statement-breakpoint
ALTER TABLE "transaction" ALTER COLUMN "type" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "transaction" drop column "type";--> statement-breakpoint
ALTER TABLE "transaction" ADD COLUMN "type" "transaction_type" GENERATED ALWAYS AS ( CASE 
    WHEN budget_id IS NOT NULL THEN 'budget'::transaction_type
    WHEN pot_id IS NOT NULL THEN 'pot'::transaction_type
    ELSE 'other'::transaction_type
  END) STORED NOT NULL;--> statement-breakpoint
ALTER TABLE "transaction" ALTER COLUMN "party_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "pot" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "transaction" ADD CONSTRAINT "transaction_budget_id_budget_id_fk" FOREIGN KEY ("budget_id") REFERENCES "public"."budget"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transaction" ADD CONSTRAINT "transaction_pot_id_pot_id_fk" FOREIGN KEY ("pot_id") REFERENCES "public"."pot"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transaction" ADD CONSTRAINT "type_check" CHECK ((budget_id IS NOT NULL AND pot_id IS NULL) OR
  (pot_id IS NOT NULL AND budget_id IS NULL) OR
  (budget_id IS NULL AND pot_id IS NULL));